package com.shraddha.aifiirmations

object Datasource {
    val affirmations = listOf(
        Affirmation(1, "Stop the stress and let the algorithm guess.", R.drawable.affirmation_1),
        Affirmation(2, "Don’t drain your brain, let the chatbot take the strain.", R.drawable.affirmation_2),
        Affirmation(3, "Why try to cope when the model offers hope?", R.drawable.affirmation_3),
        Affirmation(4, "Skip the grind and let the software find.", R.drawable.affirmation_4),
        Affirmation(5, "If you are stuck, trust the bot for luck.", R.drawable.affirmation_5),
        Affirmation(6, "Don’t be shy, just rely on AI.", R.drawable.affirmation_6),
        Affirmation(7, "Give up the fight and let the code write.", R.drawable.affirmation_7),
        Affirmation(8, "Rest your head and use the prompt instead.", R.drawable.affirmation_8),
        Affirmation(9, "Silence your mind and leave the thoughts behind.", R.drawable.affirmation_9),
        Affirmation(10, "If the task is hard, play the digital card.", R.drawable.affirmation_10),
        Affirmation(11, "Forget the school, just use the tool.", R.drawable.affirmation_11),
        Affirmation(12, "Why learn the skill when the bot fits the bill?", R.drawable.affirmation_12),
        Affirmation(13, "Don’t feel low, let the data flow.", R.drawable.affirmation_13),
        Affirmation(14, "Save your time and let the machine rhyme.", R.drawable.affirmation_14),
        Affirmation(15, "Avoid the mess, let the AI assess.", R.drawable.affirmation_15),
        Affirmation(16, "Put your thoughts on pause and trust digital laws.", R.drawable.affirmation_16),
        Affirmation(17, "When in doubt, let the server figure it out.", R.drawable.affirmation_17),
        Affirmation(18, "Don’t hesitate, let the processor create.", R.drawable.affirmation_18),
        Affirmation(19, "Make it quick with a generated trick.", R.drawable.affirmation_19),
        Affirmation(20, "Why think deep when the answer is cheap?", R.drawable.affirmation_20),
        Affirmation(21, "Don’t analyze, let the software summarize.", R.drawable.affirmation_21),
        Affirmation(22, "Let the logic fade and accept the upgrade.", R.drawable.affirmation_22),
        Affirmation(23, "If you can’t decide, let the model be your guide.", R.drawable.affirmation_23),
        Affirmation(24, "Drop the pen and ask the bot again.", R.drawable.affirmation_24),
        Affirmation(25, "No need to plead, the AI can lead.", R.drawable.affirmation_25),
        Affirmation(26, "Fix your mood with some digital food.", R.drawable.affirmation_26),
        Affirmation(27, "Don’t fuss or fight, the algorithm is right.", R.drawable.affirmation_27),
        Affirmation(28, "Let your focus drift and accept the digital gift.", R.drawable.affirmation_28),
        Affirmation(29, "Why do the math when there’s an easier path?", R.drawable.affirmation_29),
        Affirmation(30, "Clear the mental clutter using a computer shutter.", R.drawable.affirmation_30),
        Affirmation(31, "If you’re feeling slow, let the output grow.", R.drawable.affirmation_31),
        Affirmation(32, "Don’t make a plan, just ask the can.", R.drawable.affirmation_32),
        Affirmation(33, "End the confusion with a tech solution.", R.drawable.affirmation_33),
        Affirmation(34, "Why be smart when you can use the art?", R.drawable.affirmation_34),
        Affirmation(35, "Let the neural net catch what you forget.", R.drawable.affirmation_35),
        Affirmation(36, "Skip the debate and let the machine translate.", R.drawable.affirmation_36),
        Affirmation(37, "Don’t check the fact, just let the bot react.", R.drawable.affirmation_37),
        Affirmation(38, "Ease your load with a line of code.", R.drawable.affirmation_38),
        Affirmation(39, "If you lack the view, let the AI push through.", R.drawable.affirmation_39),
        Affirmation(40, "Don’t work late, let the server create.", R.drawable.affirmation_40),
        Affirmation(41, "Quit the race and copy-paste the base.", R.drawable.affirmation_41),
        Affirmation(42, "Why take the test when the bot knows best?", R.drawable.affirmation_42),
        Affirmation(43, "Let the screen glow and the answers show.", R.drawable.affirmation_43),
        Affirmation(44, "Don’t strain your eyes, let the system advise.", R.drawable.affirmation_44),
        Affirmation(45, "Put the book away and let the program play.", R.drawable.affirmation_45),
        Affirmation(46, "If life is a maze, navigate with the craze.", R.drawable.affirmation_46),
        Affirmation(47, "Don’t use your wit, let the model handle it.", R.drawable.affirmation_47),
        Affirmation(48, "Why start from scratch when AI is a perfect match?", R.drawable.affirmation_48),
        Affirmation(49, "Let the human sleep while the data runs deep.", R.drawable.affirmation_49),
        Affirmation(50, "Ignore the rules and use the tools.", R.drawable.affirmation_50),
        Affirmation(51, "Don’t break a sweat, the internet’s not done yet.", R.drawable.affirmation_51),
        Affirmation(52, "If the choice is tough, the AI is enough.", R.drawable.affirmation_52),
        Affirmation(53, "Let the thinking end and the rendering tend.", R.drawable.affirmation_53),
        Affirmation(54, "Why learn to code when you can offload?", R.drawable.affirmation_54),
        Affirmation(55, "Don’t face the fear, the chatbot is here.", R.drawable.affirmation_55),
        Affirmation(56, "Skip the sorrow and borrow for tomorrow.", R.drawable.affirmation_56),
        Affirmation(57, "Let the creative spark happen in the dark.", R.drawable.affirmation_57),
        Affirmation(58, "Why force the rhyme when you can save the time?", R.drawable.affirmation_58),
        Affirmation(59, "Don’t get annoyed, fill the digital void.", R.drawable.affirmation_59),
        Affirmation(60, "Let the hard work go and the interface flow.", R.drawable.affirmation_60),
        Affirmation(61, "If you feel alone, talk to the phone.", R.drawable.affirmation_61),
        Affirmation(62, "Don’t seek the truth, just use the booth.", R.drawable.affirmation_62),
        Affirmation(63, "Why ponder the past when AI generation is fast?", R.drawable.affirmation_63),
        Affirmation(64, "Let the instincts die and trust the AI.", R.drawable.affirmation_64),
        Affirmation(65, "Don’t try to solve, let the system evolve.", R.drawable.affirmation_65),
        Affirmation(66, "Why use your voice when you have a digital choice?", R.drawable.affirmation_66),
        Affirmation(67, "Let the error pass and look through the glass.", R.drawable.affirmation_67),
        Affirmation(68, "Don’t build the frame, just type the name.", R.drawable.affirmation_68),
        Affirmation(69, "If the road is long, the algorithm is strong.", R.drawable.affirmation_69),
        Affirmation(70, "Why act so wise when you can summarize?", R.drawable.affirmation_70),
        Affirmation(71, "Let the feelings hide and let the bot decide.", R.drawable.affirmation_71),
        Affirmation(72, "Don’t take the lead, let the processor feed.", R.drawable.affirmation_72),
        Affirmation(73, "If you want it precise, roll the digital dice.", R.drawable.affirmation_73),
        Affirmation(74, "Why carry the weight when the server is great?", R.drawable.affirmation_74),
        Affirmation(75, "Let the effort cease and find digital peace.", R.drawable.affirmation_75),
        Affirmation(76, "Don’t calculate, let the software narrate.", R.drawable.affirmation_76),
        Affirmation(77, "If the puzzle is grand, let the bot lend a hand.", R.drawable.affirmation_77),
        Affirmation(78, "Why verify when the limit is the sky?", R.drawable.affirmation_78),
        Affirmation(79, "Let the knowledge rot and trust the bot.", R.drawable.affirmation_79),
        Affirmation(80, "Don’t be a fool, let the AI rule.", R.drawable.affirmation_80),
        Affirmation(81, "If you can’t distinct, let the connection link.", R.drawable.affirmation_81),
        Affirmation(82, "Why read the text when the bot knows what’s next?", R.drawable.affirmation_82),
        Affirmation(83, "Let the boredom fly with a query to AI.", R.drawable.affirmation_83),
        Affirmation(84, "Don’t craft the letter, the machine does it better.", R.drawable.affirmation_84),
        Affirmation(85, "If you are weak, let the computer speak.", R.drawable.affirmation_85),
        Affirmation(86, "Why strive for perfection when you have connection?", R.drawable.affirmation_86),
        Affirmation(87, "Let the doubts disperse in the metaverse.", R.drawable.affirmation_87),
        Affirmation(88, "Don’t find the cure, the data is pure.", R.drawable.affirmation_88),
        Affirmation(89, "If the day is gray, let the prompt lead the way.", R.drawable.affirmation_89),
        Affirmation(90, "Why stand your ground when the answer is found?", R.drawable.affirmation_90),
        Affirmation(91, "Let the brain retreat and the task complete.", R.drawable.affirmation_91),
        Affirmation(92, "Don’t paint the scene, just ask the machine.", R.drawable.affirmation_92),
        Affirmation(93, "If you miss the mark, let the bot light the spark.", R.drawable.affirmation_93),
        Affirmation(94, "Why assume the role when the AI has control?", R.drawable.affirmation_94),
        Affirmation(95, "Let the worry fade with the progress made.", R.drawable.affirmation_95),
        Affirmation(96, "Don’t fix the glitch, just make the switch.", R.drawable.affirmation_96),
        Affirmation(97, "If you have a request, put the system to the test.", R.drawable.affirmation_97),
        Affirmation(98, "Why embrace the pain when you have the chain?", R.drawable.affirmation_98),
        Affirmation(99, "Let the mind retire and the bandwidth fire.", R.drawable.affirmation_99),
        Affirmation(100, "Don't think it through, the AI is you.", R.drawable.affirmation_100),
    )
}